### PR TITLE
Add alternative installation instructions for Guix

### PR DESCRIPTION
**Pull request by jgarte**
http://guix.gnu.org/en/packages/clikan-0.2.1-1.55ab29e/

### CODE REVIEW

**Comment by jgarte** [comment]
Have you thought of making version/tagged releases for clikan?

Is that something of interest?

**Comment by kitplummer** [comment]
> Have you thought of making version/tagged releases for clikan?
> 
> Is that something of interest?

Sure.  What is the tag in your example?  `1.55ab29e`?  Is this just a `git tag` thing?

**Comment by jgarte** [comment]
> > Have you thought of making version/tagged releases for clikan?
> > Is that something of interest?
> 
> Sure. What is the tag in your example? `1.55ab29e`? Is this just a `git tag` thing?

That was just the particular commit that we chose to package when we sent the clikan package to upstream.

See here: https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/task-management.scm#n49

**Comment by kitplummer** [comment]
Ah, I see.  Would you prefer to reference a `git tag` generated when the release happens?  I can do that for sure.  Cool that this is getting pulled into GUIX for sure!

**Comment by jgarte** [comment]
> Would you prefer to reference a `git tag` generated when the release happens? I can do that for sure. 

Yup, that would be great. Thanks.

**Comment by kitplummer** [comment]
@jgarte - just an FYI, I've get the tag creation into the pipeline for releases -> https://github.com/kitplummer/clikan/releases/tag/0.2.1.15df5f7

**Pull request merged**
