### PR TITLE
Four minor changes

### PR DESCRIPTION
**Pull request by dantam**
Four minor changes:
1. Default to CLIKAN_HOME, with fall back to HOME. Tests become repeatable, without affecting config and data files at HOME.
2. Change task_id from option to argument, reduces typing.
3. When running "configure", confirms with user before overwriting existing config file.
4. Changed function/command names ("display"->"show", "new"->"add", "remove"->"delete"). "add" is a verb, "new" is not. "-d" is often use to delete.

### CODE REVIEW

**Comment by kitplummer** [comment]
Awesome.  Am away from my desk til late tomorrow but will look this over
then.  Thanks!

**Comment by kitplummer** [comment]
Ok, so the only thing...can you update the README.md to match the new aliases?

The `configuration` test is painful - works the first time when no config file exists, but if you rerun the tests it'll bonk because it does exist.  I'd poked around with that briefly before, remember wanting to not waste too much time on it.  But like the addition of the overwrite check.

Once this is in, I'm going to bump the version since this is a bit of a big/breaking/new interface change and push to PyPi.

Thanks again.

**Comment by dantam** [comment]
Thanks! Updated README.md as requested.

The tests can be structured differently - instead of depending on a sequential run of the tests, ideally each test can run on its own, with fake config and data files. Either way, [tempfile](https://docs.python.org/3/library/tempfile.html) can help.

**Comment by dantam** [comment]
A quick work around for the tests would be to remove the test file e.g.:
`rm /tmp/.clikan.* ; CLIKAN_HOME=/tmp pytest clikan_test.py`

**Comment by dantam** [comment]
This unintentionally pulled in two more commits from my branch: flake8 clean ups that should be fine too.

**Pull request merged**
